### ISSUE TITLE
Pine Rockland - Forest Jumpstart - Project Initiation Checklist

### ISSUE THREAD

**Issue by Danielcalza** [TREC-Agroecology/plant-diversity#10]
- [ ] Land request
- [ ] UFarm
- [ ] Equipment request
- [ ] Fertilizer, herbicide, etc. purchased
- [ ] Seeds/ plant materials purchased
- [ ] Flags, paint, etc. purchased
- [ ] Plastic mulch purchased
- [ ] Irrigation materials purchased
- [ ] Miscellaneous, i.e., envelopes for seeds, bags for soil samples, etc. purchased
- [ ] Review weather patterns for weeks before and during deployment

**Comment by Danielcalza** [comment]
Please feel free to add anything else - I will be using this project as an example to put together a more specific list for off-center research activities. @brymz @cliffgmartin
