### ISSUE TITLE
2023 Plant Diversity - Project Initiation Checklist

### ISSUE THREAD

**Issue by Danielcalza** [TREC-Agroecology/plant-diversity#21]
- [ ] Land request
- [ ] UFarm
- [ ] Flags, paint, etc. purchased
- [ ] Miscellaneous, i.e., envelopes for seeds, bags for soil samples, etc. purchased
- [ ] Review weather patterns for weeks before and during deployment
